In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.datasets import load_diabetes


In [3]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

In [4]:
X,y=load_diabetes(return_X_y=True)

In [5]:
print(X.shape)
print(y.shape)

(442, 10)
(442,)


In [6]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [7]:
reg=LinearRegression()

In [8]:
reg.fit(X_train,y_train)

LinearRegression()

In [9]:
print(reg.coef_)
print(reg.intercept_)

[  -9.15865318 -205.45432163  516.69374454  340.61999905 -895.5520019
  561.22067904  153.89310954  126.73139688  861.12700152   52.42112238]
151.88331005254167


In [10]:
y_pred=reg.predict(X_test)
r2_score(y_test,y_pred)

0.4399338661568969

In [14]:
import numpy as np

class gdregressor:
    def __init__(self, learning_rate=0.01, epochs=100):
        self.coef_ = None
        self.intercept_ = None
        self.lr = learning_rate
        self.epochs = epochs

    def fit(self, X_train, y_train):
        y_train = y_train.ravel()  # ensure 1D
        self.intercept_ = 0
        self.coef_ = np.ones(X_train.shape[1])

        for i in range(self.epochs):
            y_hat = np.dot(X_train, self.coef_) + self.intercept_
            intercept_der = -2 * np.mean(y_train - y_hat)
            coef_der = -2 * np.dot(X_train.T, (y_train - y_hat)) / X_train.shape[0]
            self.intercept_ -= self.lr * intercept_der
            self.coef_ -= self.lr * coef_der

    def predict(self, X_test):
        return np.dot(X_test, self.coef_) + self.intercept_


In [15]:
gdr=gdregressor(epochs=1)


In [17]:
gdr.fit(X_train,y_train)

In [18]:
from sklearn.linear_model import SGDRegressor

In [19]:
model = SGDRegressor(max_iter=1000, tol=1e-3, learning_rate="invscaling", eta0=0.01, random_state=42)


In [20]:
model.fit(X_train,y_train)

D:\anaconda3\Lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:1616: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(


SGDRegressor(random_state=42)

In [21]:
model.predict(X_test)

array([154.39102718, 184.12294618, 145.53773943, 116.22086803,
       224.52144812, 218.78440616, 110.94979802, 119.04265338,
        99.53431286, 179.79865519, 165.00492083, 169.29669485,
       181.45810938, 156.91991371, 226.82572383, 103.05214732,
       175.99303414, 137.05606505, 144.17270988, 143.72899312,
       129.00469899, 192.64279393, 170.73473358, 176.25887723,
       129.63708885, 209.90670837, 186.4942477 , 132.93476434,
        78.81299961, 231.04904714, 223.13893864, 126.22158907,
        88.26439698, 121.50449885, 191.54221615, 165.72404663,
       167.08857643, 191.96994481, 121.23416808, 219.65944032,
       135.61515357, 132.59285732, 180.90298128, 181.52778191,
       165.97572992, 148.30748595, 171.66389717, 253.14906967,
       126.43265481, 192.08781483, 217.62620779, 128.60889428,
       141.70396104, 159.73405901, 183.68742601, 125.47589392,
       165.23459054,  98.65790979, 157.47906639, 140.47979033,
       162.53244278, 172.77420365, 119.908147  , 190.25

In [22]:
y_pred=model.predict(X_test)

In [23]:
r2_score(y_test,y_pred)

0.3932149934671314

In [24]:
model.coef_

array([  61.5825898 ,  -22.56741906,  254.61525168,  186.86869451,
         40.01655599,   11.7676827 , -140.34051217,  122.09715282,
        237.64704237,  116.74283607])

In [25]:
model.intercept_

array([151.95817133])

In [26]:
from sklearn.metrics import mean_squared_error

In [27]:
mean_squared_error(y_test,y_pred)

3352.586057627798