In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.datasets import load_diabetes


In [3]:
from sklearn.linear_model import SGDRegressor
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

In [4]:
X,y=load_diabetes(return_X_y=True)


In [7]:
print(X.shape)
print(y.shape)

(442, 10)
(442,)


In [5]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [9]:
model=SGDRegressor()

In [10]:
model.fit(X_train,y_train)

D:\anaconda3\Lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:1616: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(


SGDRegressor()

In [12]:
y_pred=model.predict(X_test)

In [13]:
r2_score(y_test,y_pred)

0.4127268580282034

In [14]:
model.coef_

array([  56.0772703 ,  -41.42019656,  262.34287086,  187.67592818,
         28.77030322,    4.01399819, -144.03340284,  133.92057058,
        218.4487468 ,  132.34138357])

In [15]:
model.intercept_

array([152.34921259])

In [6]:
print(X_train.shape[1])

10


In [8]:
import numpy as np
np.ones(X_train.shape[1])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
import numpy as np

class SGDRegressor:
    def __init__(self, learning_rate=0.01, epochs=100):
        self.coef_ = None
        self.intercept_ = None
        self.lr = learning_rate
        self.epochs = epochs

    def fit(self, X_train, y_train):
        self.intercept_ = 0
        self.coef_ = np.ones(X_train.shape[1])
        for i in range(self.epochs):
            for j in range(X_train.shape[0]):
                idx = np.random.randint(0, X_train.shape[0])
                y_hat = np.dot(X_train[idx], self.coef_) + self.intercept_
                intercept_der = -2 * (y_train[idx] - y_hat)
                coef_der = -2 * (y_train[idx] - y_hat) * X_train[idx]
                self.intercept_ -= self.lr * intercept_der
                self.coef_ -= self.lr * coef_der
        print("Final intercept:", self.intercept_)
        print("Final coefficients:", self.coef_)
    def predict(self, X_test):
        return np.dot(X_test, self.coef_) + self.intercept_


In [13]:
sgd=SGDRegressor(learning_rate=0.01,epochs=50)

In [14]:
sgd.fit(X_train,y_train)

Final intercept: 145.73399696385954
Final coefficients: [  57.29677895 -101.30044914  374.61611791  257.43284496   -1.36472843
  -31.7283206  -182.09376737  147.26773714  273.27148247  150.51601107]


In [15]:
y_pred=sgd.predict(X_test)

In [16]:
r2_score(y_test,y_pred)

0.43590683961568

In [17]:
print(sgd.intercept_)

145.73399696385954


In [18]:
print(sgd.coef_)

[  57.29677895 -101.30044914  374.61611791  257.43284496   -1.36472843
  -31.7283206  -182.09376737  147.26773714  273.27148247  150.51601107]
